// Dados mockados de produtos
export const produtos = [
    {
        id: '1',
        nome: 'Camiseta Esportiva Dry-Fit',
        categoria: 'camisas',
        preco: 79.90,
        desconto: 15,
        imagem: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400',
        imagens: [
            'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400',
            'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=400'
        ],
        descricao: 'Camiseta esportiva com tecnologia dry-fit para máxima transpiração.',
        descricaoCompleta: 'Camiseta esportiva de alta performance com tecnologia dry-fit que mantém você seco durante todo o treino. Material respirável e leve, perfeito para atividades físicas intensas. Disponível em vários tamanhos e cores.',
        tamanhos: ['P', 'M', 'G', 'GG'],
        cores: ['Preto', 'Branco', 'Azul', 'Cinza'],
        maisVendido: true,
        icone: 'fas fa-tshirt'
    },
    {
        id: '2',
        nome: 'Short Esportivo Pro',
        categoria: 'shorts',
        preco: 89.90,
        desconto: 0,
        imagem: 'https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=400',
        descricao: 'Short esportivo com tecido elástico e bolso para chaves.',
        descricaoCompleta: 'Short esportivo de alta qualidade com tecido elástico que proporciona máxima liberdade de movimento. Possui bolso interno para guardar chaves e objetos pequenos durante o treino.',
        tamanhos: ['P', 'M', 'G', 'GG'],
        cores: ['Preto', 'Azul', 'Cinza'],
        maisVendido: true,
        icone: 'fas fa-running'
    },
    {
        id: '3',
        nome: 'Meias Esportivas Antiderrapantes',
        categoria: 'meias',
        preco: 29.90,
        desconto: 20,
        imagem: 'https://images.unsplash.com/photo-1586350977773-bf6de6ffb897?w=400',
        descricao: 'Meias com tecnologia antiderrapante e proteção no calcanhar.',
        descricaoCompleta: 'Meias esportivas desenvolvidas com tecnologia antiderrapante e proteção extra no calcanhar. Material que evita mau odor e proporciona conforto durante todo o dia.',
        tamanhos: ['P', 'M', 'G'],
        cores: ['Branco', 'Preto', 'Cinza'],
        maisVendido: false
    },
    {
        id: '4',
        nome: 'Tênis Runner Elite',
        categoria: 'tenis',
        preco: 299.90,
        desconto: 25,
        imagem: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400',
        imagens: [
            'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400',
            'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=400'
        ],
        descricao: 'Tênis para corrida com amortecimento avançado e design moderno.',
        descricaoCompleta: 'Tênis de corrida de alta performance com sistema de amortecimento avançado que reduz o impacto nas articulações. Solado antiderrapante e design ergonômico para máxima performance.',
        tamanhos: ['36', '37', '38', '39', '40', '41', '42', '43', '44'],
        cores: ['Preto', 'Branco', 'Azul'],
        maisVendido: true,
        icone: 'fas fa-shoe-prints'
    },
    {
        id: '5',
        nome: 'Boné Esportivo Ajustável',
        categoria: 'bones',
        preco: 49.90,
        desconto: 10,
        imagem: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=400',
        descricao: 'Boné com ajuste traseiro e proteção UV.',
        descricaoCompleta: 'Boné esportivo ajustável com proteção UV 50+. Ideal para atividades ao ar livre, proporciona sombra e proteção contra raios solares.',
        tamanhos: ['Único'],
        cores: ['Preto', 'Branco', 'Azul', 'Vermelho'],
        maisVendido: false
    },
    {
        id: '6',
        nome: 'Faixa para Cabeça Esportiva',
        categoria: 'faixas',
        preco: 19.90,
        desconto: 0,
        imagem: 'https://images.unsplash.com/photo-1515856046418-8fe0f0e6852e?w=400',
        descricao: 'Faixa absorvente de suor com material elástico.',
        descricaoCompleta: 'Faixa para cabeça feita com material absorvente que mantém o suor longe dos olhos. Elástico e confortável, perfeito para todos os tipos de treino.',
        tamanhos: ['Único'],
        cores: ['Preto', 'Branco', 'Vermelho', 'Azul'],
        maisVendido: false
    },
    {
        id: '7',
        nome: 'Jaqueta Esportiva Windbreaker',
        categoria: 'jaquetas',
        preco: 159.90,
        desconto: 30,
        imagem: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400',
        descricao: 'Jaqueta corta-vento leve e impermeável.',
        descricaoCompleta: 'Jaqueta esportiva corta-vento com proteção impermeável. Leve e respirável, ideal para treinos ao ar livre em qualquer condição climática.',
        tamanhos: ['P', 'M', 'G', 'GG'],
        cores: ['Preto', 'Azul', 'Vermelho'],
        maisVendido: true,
        icone: 'fas fa-vest'
    },
    {
        id: '8',
        nome: 'Casaco Esportivo com Capuz',
        categoria: 'casacos',
        preco: 199.90,
        desconto: 20,
        imagem: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=400',
        descricao: 'Casaco quente com capuz e bolsos laterais.',
        descricaoCompleta: 'Casaco esportivo com capuz e isolamento térmico. Perfeito para treinos em climas mais frios. Possui bolsos laterais para guardar objetos pessoais.',
        tamanhos: ['P', 'M', 'G', 'GG'],
        cores: ['Preto', 'Cinza', 'Azul'],
        maisVendido: false
    },
    {
        id: '9',
        nome: 'Moletom Esportivo Confort',
        categoria: 'moletons',
        preco: 129.90,
        desconto: 15,
        imagem: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400',
        descricao: 'Moletom quente e confortável para treinos e dia a dia.',
        descricaoCompleta: 'Moletom esportivo com tecido macio e quente. Ideal para aquecimento pré-treino ou uso casual. Design moderno e confortável.',
        tamanhos: ['P', 'M', 'G', 'GG'],
        cores: ['Preto', 'Cinza', 'Azul'],
        maisVendido: true,
        icone: 'fas fa-tshirt'
    },
    {
        id: '10',
        nome: 'Touca Esportiva Térmica',
        categoria: 'toucas',
        preco: 34.90,
        desconto: 0,
        imagem: 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400',
        descricao: 'Touca térmica para proteção contra o frio.',
        descricaoCompleta: 'Touca esportiva térmica que mantém a cabeça aquecida durante treinos ao ar livre em climas frios. Material elástico e confortável.',
        tamanhos: ['Único'],
        cores: ['Preto', 'Cinza', 'Azul', 'Vermelho'],
        maisVendido: false
    },
    {
        id: '11',
        nome: 'Camiseta Manga Longa Esportiva',
        categoria: 'camisas',
        preco: 99.90,
        desconto: 0,
        imagem: 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=400',
        descricao: 'Camiseta manga longa com compressão para melhor performance.',
        descricaoCompleta: 'Camiseta esportiva manga longa com tecnologia de compressão que melhora a circulação sanguínea e reduz fadiga muscular. Ideal para treinos de força e resistência.',
        tamanhos: ['P', 'M', 'G', 'GG'],
        cores: ['Preto', 'Azul', 'Vermelho'],
        maisVendido: false
    },
    {
        id: '12',
        nome: 'Short de Compressão',
        categoria: 'shorts',
        preco: 69.90,
        desconto: 25,
        imagem: 'https://images.unsplash.com/photo-1594938291221-94f18cbb5663?w=400',
        descricao: 'Short com tecnologia de compressão para recuperação muscular.',
        descricaoCompleta: 'Short de compressão que melhora a circulação e acelera a recuperação muscular. Perfeito para pós-treino e atividades de alta intensidade.',
        tamanhos: ['P', 'M', 'G'],
        cores: ['Preto', 'Azul'],
        maisVendido: false
    },
    {
        id: '13',
        nome: 'Tênis Cross Training',
        categoria: 'tenis',
        preco: 349.90,
        desconto: 0,
        imagem: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=400',
        descricao: 'Tênis versátil para cross training e musculação.',
        descricaoCompleta: 'Tênis desenvolvido especificamente para cross training e musculação. Solado plano e estável, ideal para levantamento de peso e exercícios funcionais.',
        tamanhos: ['38', '39', '40', '41', '42', '43', '44'],
        cores: ['Preto', 'Branco'],
        maisVendido: true,
        icone: 'fas fa-shoe-prints'
    },
    {
        id: '14',
        nome: 'Jaqueta Softshell Premium',
        categoria: 'jaquetas',
        preco: 229.90,
        desconto: 35,
        imagem: 'https://images.unsplash.com/photo-1578587018452-892bacefd3f2?w=400',
        descricao: 'Jaqueta softshell de alta qualidade com proteção total.',
        descricaoCompleta: 'Jaqueta softshell premium com proteção contra vento, chuva leve e frio. Tecnologia de respirabilidade avançada para máxima performance.',
        tamanhos: ['P', 'M', 'G', 'GG'],
        cores: ['Preto', 'Azul', 'Vermelho'],
        maisVendido: false
    },
    {
        id: '15',
        nome: 'Moletom com Zíper',
        categoria: 'moletons',
        preco: 149.90,
        desconto: 20,
        imagem: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=400',
        descricao: 'Moletom com zíper frontal e capuz ajustável.',
        descricaoCompleta: 'Moletom esportivo com zíper frontal e capuz ajustável. Bolsos laterais e punhos ajustáveis. Perfeito para treinos e uso casual.',
        tamanhos: ['P', 'M', 'G', 'GG'],
        cores: ['Preto', 'Cinza', 'Azul'],
        maisVendido: true,
        icone: 'fas fa-tshirt'
    },
    {
        id: '16',
        nome: 'Kit Meias Esportivas (3 pares)',
        categoria: 'meias',
        preco: 49.90,
        desconto: 30,
        imagem: 'https://images.unsplash.com/photo-1586350977773-bf6de6ffb897?w=400',
        descricao: 'Kit com 3 pares de meias esportivas de alta qualidade.',
        descricaoCompleta: 'Kit econômico com 3 pares de meias esportivas. Tecnologia antiderrapante, proteção no calcanhar e material que evita mau odor.',
        tamanhos: ['P', 'M', 'G'],
        cores: ['Branco', 'Preto'],
        maisVendido: false
    },
    {
        id: '17',
        nome: 'Boné Snapback',
        categoria: 'bones',
        preco: 59.90,
        desconto: 15,
        imagem: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=400',
        descricao: 'Boné snapback ajustável com design moderno.',
        descricaoCompleta: 'Boné snapback com ajuste traseiro. Design moderno e confortável, perfeito para complementar seu look esportivo.',
        tamanhos: ['Único'],
        cores: ['Preto', 'Branco', 'Azul'],
        maisVendido: false
    },
    {
        id: '18',
        nome: 'Casaco Térmico Esportivo',
        categoria: 'casacos',
        preco: 179.90,
        desconto: 0,
        imagem: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400',
        descricao: 'Casaco térmico para proteção contra o frio intenso.',
        descricaoCompleta: 'Casaco térmico esportivo com isolamento interno. Perfeito para treinos em temperaturas baixas. Leve e respirável.',
        tamanhos: ['P', 'M', 'G', 'GG'],
        cores: ['Preto', 'Cinza'],
        maisVendido: false
    },
    {
        id: '19',
        nome: 'Kit Faixas para Cabeça (5 un)',
        categoria: 'faixas',
        preco: 29.90,
        desconto: 40,
        imagem: 'https://images.unsplash.com/photo-1515856046418-8fe0f0e6852e?w=400',
        descricao: 'Kit com 5 faixas absorventes em cores variadas.',
        descricaoCompleta: 'Kit econômico com 5 faixas para cabeça em cores variadas. Material absorvente e elástico, perfeito para vários treinos.',
        tamanhos: ['Único'],
        cores: ['Multicolor'],
        maisVendido: false
    },
    {
        id: '20',
        nome: 'Touca de Lã Esportiva',
        categoria: 'toucas',
        preco: 39.90,
        desconto: 25,
        imagem: 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400',
        descricao: 'Touca de lã macia e quente para inverno.',
        descricaoCompleta: 'Touca de lã esportiva macia e quente. Perfeita para manter a cabeça aquecida durante treinos em climas muito frios.',
        tamanhos: ['Único'],
        cores: ['Preto', 'Cinza', 'Azul'],
        maisVendido: false
    }
];

